# Generated by Django 5.2.8 on 2025-11-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('checkout_request_id', models.CharField(default='', max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
